theme: jekyll-theme-cayman
show_downloads: "true"
title: "Modern Audio Tagger"
description: "Modern Audio Tagger is a powerful tool that allows to reorganize your music library with a comfortable UI or an awesome shell"
author: "Starred MediaSoft"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
